### ISSUE TITLE
Does the JNI library respect OMP_NUM_THREADS or OPENBLAS_NUM_THREADS environment to controlling the number of thread used ?

### ISSUE THREAD

**Issue by WeichenXu123** [luhenry/netlib#14]
Does the JNI library respect OMP_NUM_THREADS or OPENBLAS_NUM_THREADS environment to controlling the number of thread used ?

In my test, I found no matter which value I set for these 2 variables, the performance always decreases when parallelism increased. I guess the library does not handle the environment correctly.

**Comment by luhenry** [comment]
@WeichenXu123 the JNI library doesn't use these values directly. These values are going to be available to the libblas.so.3 library that's being used, so if this library is OpenBLAS then it's going to make use of it.
