### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by JD557** [luhenry/netlib#3]
The Read Me seems quite empty. I have some questions about this library that I couldn't find the answers.

Some points that I think would be nice to cover:
- What are the supported backends (native, f2j...)?
  - How can the user of a library (like Breeze or Spark) change the backend? (like https://github.com/fommil/netlib-java#customisation)
  - Are the native binaries distributed with the lib? How can a end user pick, for example, only the mac OS binaries (like the bytedeco classifiers in smile: https://github.com/haifengl/smile)
  - Can the user force a certain BLAS implementation, like MKL? (in the bytedeco libraries, this could be achived by setting `-Dorg.bytedeco.openblas.load=mkl_rt`, for example)
- What's the difference between JDK versions? The README seems to imply that JDK 16+ is required, but this seems to work fine on JDK 8, and fcb00ffd585da69f4d779e965a2ddbba5436ee93 points to a JDK 17+ feature.

Sorry if I sound pushy or if some of the questions don't make sense. I would send a PR but, unfortunately, I don't know the answer to those questions 😛

**Comment by luhenry** [comment]
@JD557, thank you for this issue. These are questions that indeed need answers. I'll get to it this week.

**Comment by luhenry** [comment]
@JD557 I finally updated the https://github.com/luhenry/netlib/blob/master/README.md. Let me know if it answers your questions and if anything is missing or unclear. Thanks!

**Comment by JD557** [comment]
Looks great! Thanks for your time.
