### ISSUE TITLE
Cannot use OpenBlas on Mac: Lapack references dgegs but this method is deprecated and not available anymore

### ISSUE THREAD

**Issue by pmeheut** [luhenry/netlib#9]
I've managed to compile everything on BigSur and had to make some changes but everything works fine until I try to use a native implementation of Lapack.
It tries to load dgegs but this symbol has been deprecated: see https://docs.oracle.com/cd/E19957-01/816-2461/dgegs.html for instance.
Any solution?

**Comment by pmeheut** [comment]
Yes it would work. Thanks.

**Comment by luhenry** [comment]
Fixed in https://github.com/luhenry/netlib/commit/8f7aa38400bc9668a3e028ffe72381692d305966
